### ISSUE TITLE
What is the format for --custom gradients?

### ISSUE THREAD

**Issue by u0398** [mazznoer/lolcrab#12]
The `--custom` option color format does not seem to be defined anywhere. I've tried every combination of hex values I can think of, but always get the error `invalid hex format`.

What is the custom gradient format?

**Comment by mazznoer** [comment]
It should work with named colors, hex, rgb, etc. What hex that gives you error?

![IMG_20240807_094229](https://github.com/user-attachments/assets/cc64f66a-034b-43a9-ae3f-045170f0a0c7)

**Comment by u0398** [comment]
Well, I just looked at what I was trying last night, and realized I was making a trivial mistake.

This worked:
```lolcrab <file>```

But when I tried something like this it failed:
```lolcrab -c 00ff00 ff0000 0000ff <file>```

In retrospect it was trivial mistake. The returned error even said that `<file>` was an invalid color.
