### ISSUE TITLE
Windows funkiness

### ISSUE THREAD

**Issue by fdncred** [mazznoer/lolcrab#2]
I'm wondering why in Windows `dir | lolcrab -i` looks like this. This is just with command prompt cmd.exe but it looks the same with powershell.exe/pwsh.exe.
![image](https://user-images.githubusercontent.com/343840/133438744-4e63901c-308c-45a1-91d7-b16c29a30f57.png)

But if I use `lsd -l | lolcrab -i` , in the same folder, it looks like this. [lsd github link](https://github.com/Peltoche/lsd)
![image](https://user-images.githubusercontent.com/343840/133438905-fba3b611-c475-426c-b164-86bd1881a0ae.png)

Could different line endings perhaps cause this?

btw - this output, when it works, is way cool! thanks for this!!!

**Comment by mazznoer** [comment]
I updated the code so it now handles crlf line endings. Please try using the latest commit.

**Comment by fdncred** [comment]
Ahhh, so beautiful. Thanks for the fix!

![image](https://user-images.githubusercontent.com/343840/133611553-cf4e34e6-ef0a-4853-96a4-58cd867cd6a1.png)

**Comment by mazznoer** [comment]
Thank you for the bug report. I am glad you like it.
