### ISSUE TITLE
Mangles some Unicode characters and NerdFont glyphs.

### ISSUE THREAD

**Issue by Terraphice** [mazznoer/lolcrab#7]
Particularly it wrecked my Unicode pipe characters as well as all the nerd font glyphs. Should probably not change NF glyphs, but definitely should work with the pipe characters. No matter what, it shouldn't be garbling things.

I use Windows 11 btw.

![image](https://user-images.githubusercontent.com/41020526/194904605-f620c4b8-940c-4e8c-819d-ddadb25d4be7.png)

I gave this project a shot because of the funny crab name and now I'm sad. :(

**Comment by Terraphice** [comment]
(Oh, I should also mention it mangles Greek as well. Safe to assume it doesn't handle any non-ASCII English characters, I guess.)

**Comment by mazznoer** [comment]
![lolcrab-unicode](https://user-images.githubusercontent.com/56464409/195326119-ff2cd044-6f60-44df-b696-30bd44c8ae0a.png)

My test with Greek and some unicode symbols is looks fine. I am not sure what is causing the problem.

**Comment by Terraphice** [comment]
Perhaps it's a font issue? Or locale? What's your font? Locale? Language?

**Comment by Terraphice** [comment]
After further testing, it seems it only mangles my Neofetch output. I can only presume it's because of the special color coding Neofetch has? No clue.

**Comment by Terraphice** [comment]
Closed since this was an issue with Neofetch, and Neofetch is now unmaintained. Consider a new issue with Hyfetch or another successor if someone wants this fixed in the future.
